Adding the min version on Stats calculator
clarifyhealth/spark-sparse-vector pull request #64
Opened 2021-03-16 17:34 UTC by rtamiri

2021-03-17 00:00 UTC, roman-y requested changes

2021-03-17 00:00 UTC, roman-y commented on src/main/scala/com/clarify/stats/slim/StatsCalculator.scala
> +package com.clarify.stats.slim
I don't like its path src/main/scala/com/clarify/stats/slim/StatsCalculator.scala
it's inconsistent with src/main/scala/com/clarify/stats/v1/StatsCalculator.scala
I'd say rename this file to StatsCalculatorSlim.scala and add it to src/main/scala/com/clarify/stats/v1/

2021-03-18 15:23 UTC, rtamiri commented on src/main/scala/com/clarify/stats/slim/StatsCalculator.scala
> +object StatsCalculator {
fixed

2021-03-18 15:24 UTC, rtamiri commented on src/main/scala/com/clarify/stats/slim/StatsCalculator.scala
> +package com.clarify.stats.slim
The folder path should contain one Scala file. I can create another new folder

2021-03-18 16:57 UTC, roman-y commented on src/main/scala/com/clarify/stats/slim/StatsCalculator.scala
> +package com.clarify.stats.slim
"The folder path should contain one Scala file" - why?

2021-03-19 09:07 UTC, rtamiri commented on src/main/scala/com/clarify/stats/slim/StatsCalculator.scala
> +package com.clarify.stats.slim
I mean for consistency with other scripts in the repo.

2021-03-19 16:46 UTC, roman-y commented on src/main/scala/com/clarify/stats/slim/StatsCalculator.scala
> +package com.clarify.stats.slim
I don't know of such rule and I don't see that it's being followed eg https://github.com/clarifyhealth/spark-sparse-vector/tree/master/src/main/scala/com/clarify/prediction_explainer
So still unclear as to what the reason is. If you want to be consistent why are you creating folder `slim` on the same level where we create version folders like `v1`?

2021-03-19 18:35 UTC, rtamiri commented on src/main/scala/com/clarify/stats/slim/StatsCalculator.scala
> +package com.clarify.stats.slim
fixed

2021-03-19 18:56 UTC, roman-y approved these changes

2021-03-19 18:58 UTC, merged